# BUILD (in root directory)

load("@rules_cc//cc:cc_binary.bzl", "cc_binary")

cc_binary(
    name = "hello_world",
    srcs = ["main.cc"],
    # No toolchain specified here - relies on registration and auto-detection
)
